package com.codename1.helloiap;


import com.codename1.components.ToastBar;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.payment.Purchase;
import com.codename1.payment.PurchaseCallback;
import com.codename1.payment.RestoreCallback;
import com.codename1.ui.Button;
import com.codename1.ui.FontImage;
import com.codename1.ui.Toolbar;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class HelloWorldIAP implements PurchaseCallback, RestoreCallback {
    public static final String SKU_WORLD = "com.codename1.world";
    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form("Hi World");
        Button buyWorld = new Button("Buy World");
        buyWorld.addActionListener(e->{
            if (Purchase.getInAppPurchase().wasPurchased(SKU_WORLD)) {
                Dialog.show("Can't Buy It", "You already Own It", "OK", null);
            } else {
                Purchase.getInAppPurchase().purchase(SKU_WORLD);
            }
        });
       
        // Apple requires that you provide an option to restore purchases.
        Purchase iap = Purchase.getInAppPurchase();
        if (iap.isRestoreSupported()) {
            Button restorePurchases = new Button("Restore Purchases");
            restorePurchases.addActionListener(e->{
                iap.restore();
            });
            hi.addComponent(restorePurchases);
        }
        
        hi.addComponent(buyWorld);
        
        hi.show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

    @Override
    public void itemPurchased(String sku) {
        ToastBar.showMessage("Thanks.  You now own the world", FontImage.MATERIAL_THUMB_UP);
    }

    @Override
    public void itemPurchaseError(String sku, String errorMessage) {
        ToastBar.showErrorMessage("Failure occurred: "+errorMessage);
    }

    @Override
    public void itemRefunded(String sku) {
        
    }

    @Override
    public void subscriptionStarted(String sku) {
        
    }

    @Override
    public void subscriptionCanceled(String sku) {
        
    }

    @Override
    public void paymentFailed(String paymentCode, String failureReason) {
        
    }

    @Override
    public void paymentSucceeded(String paymentCode, double amount, String currency) {
        
    }

    @Override
    public void itemRestored(String sku) {
        ToastBar.showMessage("Thanks.  Your purchase has been restored", FontImage.MATERIAL_THUMB_UP);
    }

    @Override
    public void restoreRequestComplete() {
        
    }

    @Override
    public void restoreRequestError(String message) {
        ToastBar.showErrorMessage("Failure occurred: "+message);
    }

}
